### ISSUE TITLE
(re)design and discuss command line interface

### ISSUE THREAD

**Issue by cgcostume** [p-otto/glkernel#1]
This issue should be used to identify constraints and requirements and subsequently to derive and discuss the command line interface of glkernel before implementing or refining one.

**Comment by cgcostume** [comment]
Please discuss here if and why cppassist/cmdline should be used as basis for parsing arguments. Any missing feature should rather be implemented in cmdline instead of using another 3rdp.

**Comment by cgphilipp** [comment]
The goal is to have one command line tool for exporting kernels which is called `glkernel-cli`.
It should be called like this: `glkernel-cli --input [kernel-description] --output [output-file]`.

`[kernel-description]` will be a JSON file or a scripting based description of the kernel.
`[output-file]` will be a file containing the kernel data. The format of the output file will be extracted from the file ending of `[output-file]`. We target to implement at least JSON and one kind of image format (PNG?).

Additionally a meta information file should be saved, which contains dimensionality, cell type and the code used to generate the kernel. This file will be called the same as `[output-file]`, but with a custom file ending (.kernel).

`[kernel-description]` should also be able to be a previously generated kernel (see #2), in order to convert it to another format. We will probably limit this feature to loading of JSON kernels though.
For this, we might need another binary option to distinguish between kernel-descriptions and generated kernels (`-d`, `-k` ?).

If we manage to get to milestone 4, we will also have to think about creating another CLI tool for plotting kernels.

**Comment by j-beyer** [comment]
Example usage:
![screenshot-area-2017-11-20-171403](https://user-images.githubusercontent.com/11978152/33028503-6c562d10-ce16-11e7-9fce-a5e796410f8b.png)

**Comment by cgphilipp** [comment]
-  We should post an issue to cppassist to support `-i [argument]` etc.
-  Maybe add a `--format` option instead of detecting by file ending
-  Input file should be same as meta file -> dimensionality, components, used code to generate

**Comment by cgphilipp** [comment]
We can also look at how arboretum implements the CLI interface.

**Comment by j-beyer** [comment]
Willy suggested to use the cppassist::CommandLineProgram.
We will use the following CommandLineOptions:
--input, -i <inFile> (mandatory)
--output, -o <outFile> (mandatory)
--format, -f <format> (optional, if not given: try to extract ending from --output parameter, if that fails: default to json)

We will use two CommandLineActions: `generate` and `convert`
The question here is, whether we should invoke those actions explicitly via CommandLineCommands (e.g., `glkernel-cli convert -i ... -o ... -f ...`), or implicitly, by adding a non-optional switch to the convert-command (e.g., `glkernel-cli -i ... -o ... -f ... --convert/-c`)

Additionally, we will not generate a meta file, as we realized that the kernel description already holds all the meta information.

**Comment by j-beyer** [comment]
We now decided for the --convert/-c flag

**Comment by j-beyer** [comment]
```
$ ./glkernel-clid
glkernel-cli 0.2.0

A command line interface for generating and converting kernels.

usage: glkernel-cli [--convert] --input <inFileName> --output <outFileName> [--format <outFileFormat>]

Options:
 -c, --convert  Convert an existing kernel into another representation instead of generating a new one
 -f, --format   File format for the generated / converted kernel (e.g. json, png)
 -o, --output   File that the generated / converted kernel will be written to
 -i, --input    Kernel description or generated kernel

$ ./glkernel-clid -i infile.json -o outfile.png -f png
Using kernel description "infile.json" to generate kernel "outfile.png" (format: png)

$ ./glkernel-clid -i infile.json -o outfile.png
Using kernel description "infile.json" to generate kernel "outfile.png" (format: png)

$ ./glkernel-clid -i infile.json -o outfile
Using kernel description "infile.json" to generate kernel "outfile" (format: json)

$ ./glkernel-clid -c -i kernel.json -o outfile.png -f png
Converting kernel "kernel.json" to output file "outfile.png" (format: png)

$ ./glkernel-clid --c -i kernel.json -o outfile.png -f png
Generate a kernel from a kernel description or convert an existing kernel into another representation

usage: glkernel-cli [--convert] --input <inFileName> --output <outFileName> [--format <outFileFormat>]

Options:
 -c, --convert  Convert an existing kernel into another representation instead of generating a new one
 -f, --format   File format for the generated / converted kernel (e.g. json, png)
 -o, --output   File that the generated / converted kernel will be written to
 -i, --input    Kernel description or generated kernel

Error: Unknown option '--c'
```

**Comment by j-beyer** [comment]
--convert obsolet
prüfen ob "data" in description vorhanden

--input obsolet

--output optional
wenn output nicht vorhanden: input description um data erweitern
wenn output vorhanden: in neues .json / .png schreiben

**Comment by j-beyer** [comment]
$ glkernel-cli input.js [-o output.format] [-f format] => generate (default: input.json)
$ glkernel-cli input.json [-o output.format] [-f format] => convert (default: input.png)
