### ISSUE TITLE
plan and discuss scripting and serialization capabilities

### ISSUE THREAD

**Issue by cgcostume** [p-otto/glkernel#2]
This issue should be used to gather information if and how glkernel api should be exposed for scripting using [cppexpose](https://github.com/cginternals/cppexpose) and if this makes any other input serialization except for script obsolete.

**Comment by cgphilipp** [comment]
We will need to register the glkernel functions in the scripting language, so we need to be sure that this feature is supported by the scripting library.

We plan to research multiple scripting APIs:
- Javascript
  - cppexpose
  - v8pp: https://github.com/pmed/v8pp
  - nbind: https://github.com/charto/nbind
  - dukglue: https://github.com/Aloshi/dukglue
- Python
  - Boost.Python: http://www.boost.org/doc/libs/1_65_1/libs/python/doc/html/index.html
- Ruby
  - Rice: https://github.com/jasonroelofs/rice

Additionally to loading scripting files, we want to directly load a serialized kernel file (probably JSON), so that it can be exported to other formats, e.g. images.

**Comment by cgphilipp** [comment]
We need to support importing of kernels and operating on them.
One easy case to start with would be madd of two imported kernels.

We also want to iterate over kernels in the scripting language.

Make sure the error messages are parseable.

**Comment by cgphilipp** [comment]
-  Create glkernel object on Javascript side that is an array and adds functions to prototype
-  Provide boilerplate (with _) functions on C++ side that are called by Javascript object
