### ISSUE TITLE
Better error messages for JavaScript errors

### ISSUE THREAD

**Issue by j-beyer** [p-otto/glkernel#52]
Currently, the error messages from the engine are not as helpful as they could be, example:
`kernel.shuffle.foo(5)` produces `TypeError: undefined not callable`, without giving information that the `foo` is the problem.
In the current google chrome engine, the error message would `TypeError: kernel.shuffle.foo is not a function`.

Is it feasible for us to try and improve the error messages?

**Comment by Tobias1595** [comment]
This problem lies within duktape, the JS engine used by cppexpose. To get different error messages, you would need to either update duktape itself, or hook up an alternative engine to cppexpose. Both solutions are outside this project's scope.

A last solution would be to parse the error messages (currently they are just passed through), and rephrase them. This, IMO would be rather ugly.
